apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterjellyfin.fullname" . }}-ssh-pubkey
  namespace: {{ .Release.Namespace }}
data:
  # This will be populated by a job that generates the SSH key
  id_rsa.pub: ""
